spring.application.name=logsapi

#spring.datasource.driver-class-name=org.postgresql.Driver
# === OAuth2 Client (example: Google) ===
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.google.client-name=Google
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code

spring.security.oauth2.client.provider.google.issuer-uri=https://accounts.google.com

# URL of your React app for post-login redirect
app.frontend.redirect-url=https://log-monitoring-frontend.onrender.com
# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jwt.secret-base64=${JWT_SECRET_BASE64:}
