spring.application.name=logsapi
# ===============================
# PostgreSQL (Render)
# ===============================
#spring.datasource.url=${DATABASE_URL}
spring.datasource.url=jdbc:postgresql://dpg-d4ldenqli9vc73e7t160-a:5432/logsdb2
spring.datasource.username=logsdb2_user
spring.datasource.password=vSMPBzM645Aa8A5drDRNxIy0hlhbhTXO
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
