spring.application.name=logsapi
# ===============================
# PostgreSQL (Render)
# ===============================
#spring.datasource.url=${DATABASE_URL}
#spring.datasource.url=jdbc:postgresql://dpg-d6fi5gbh46gs7390h0m0-a.singapore-postgres.render.com/logs_pg_db
#spring.datasource.username=logs_pg_db_user
#spring.datasource.password=61jWiPP59ZvVYFKzeZDu4eFxigcwsRhS
#spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jwt.secret-base64=yV3gq1n8Q4vR9sA7mT1KpV2zU0xY6bC3d4e5f6g7h8=
